enum TILE_EFFECTS
	// * general *
	FX_SPLASH         :=  0x352d, //
	FX_EXPLODE_1      :=  0x36ca, //
	FX_EXPLODE_2      :=  0x36bd, //
	FX_EXPLODE_3      :=  0x36b0, //
	FX_FIREBALL       :=  0x36d4, //
	FX_MAGIC_ARROW    :=  0x36e4, //
	FX_FIRE_BOLT      :=  0x36f4, // Firesnake. (pagan?)
	FX_EXPLODE_BALL   :=  0x36fe, // Not used.

	FX_FLAMESTRIKE    :=  0x3709, //
	FX_SMOKE          :=  0x3728,
	FX_TELE_VANISH    :=  0x372a, // Teleport vanish.
	FX_SPELL_FAIL     :=  0x3735, //
	FX_BLESS_EFFECT   :=  0x373a, //
	FX_CURSE_EFFECT   :=  0x374a, //
	FX_SPARK_EFFECT   :=  0x375a, //
	FX_HEAL_EFFECT    :=  0x376a, //
	FX_MARK_EFFECT    :=  0x3779,
	FX_BLUEMOONSTART  :=  0x3789, // Deathvortex?
	FX_ENERGY_BOLT    :=  0x379f, //
	FX_BLADES_EMERGE  :=  0x37a0, // Not used.
	FX_GLOW           :=  0x37b9, // Not used.
	FX_GLOW_SPIKE     :=  0x37c3, // Not used.
	FX_DEATH_FUNNEL   :=  0x37cc, //
	FX_BLADES         :=  0x37eb, //
	FX_STATIC         :=  0x3818, // Not used. (pink static)
	FX_POISON_F_EW    :=  0x3914, // Poison field.
	FX_POISON_F_NS    :=  0x3920, // Poison field.
	FX_ENERGY_F_EW    :=  0x3947, // Energy field.
	FX_ENERGY_F_NS    :=  0x3956, // Energy field.
	FX_PARA_F_EW      :=  0x3967, // Paralyze field.
	FX_PARA_F_NS      :=  0x3979, // Paralyze field.
	FX_FIRE_F_EW      :=  0x398c, // Fire field.
	FX_FIRE_F_NS      :=  0x3996,  // Fire field.

	FX_POISON_GAS     := 0x113a
endenum
