/////////////////////////////////////////////////////////////////////////////
//
// include/effects.inc - special effects declarations
//
/////////////////////////////////////////////////////////////////////////////

Const MOVING_EFFECT_FIREBALL		:= 0x36D4;
Const MOVING_EFFECT_FROST		:= 0x373a;

Const MOVING_EFFECT_ARROW		:= 0x0f42;
Const MOVING_EFFECT_BOLT			:= 0x1bfe;

Const EFFECT_FIZZLE				:= 0x3735;
Const EFFECT_RESIST				:= 0x374a;
Const EFFECT_BLUE_SPARKLE		:= 0x373a;
Const EFFECT_RED_SPARKLE			:= 0x374a;

Const EFFECT_SPARKLE_1			:= 0x375a;
Const EFFECT_SPARKLE_2			:= 0x376a;
Const EFFECT_SPARKLE_3			:= 0x3779;

Const SFX_DRINK				:= 0x32;
Const SFX_CURE				:= 0x1e1;
Const SFX_HEAL				:= 0x1f3;


