use uo;

enum VITALS
	HITS			:= "Hits",
	MANA			:= "Mana",
	STAMINA			:= "Stamina",
	HUNGER			:= "Hunger"
endenum

enum STATS
	STRENGTH		:= "Strength",
	DEXTERITY		:= "Dexterity",
	INTELLIGENCE		:= "Intelligence"
endenum

enum SKILLS
	ALCHEMY			:= "Alchemy",
	ANATOMY			:= "Anatomy",
	ANIMAL_LORE		:= "AnimalLore",
	ITEM_IDENTIFICATION	:= "ItemIdentification",
	ARMS_LORE		:= "ArmsLore",
	PARRY			:= "Parry",
	BEGGING			:= "Begging",
	BLACKSMITHY		:= "Blacksmithy",
	BOWCRAFT_FLETCHING	:= "BowcraftFletching",
	PEACEMAKING		:= "Peacemaking",
	CAMPING			:= "Camping",
	CARPENTRY		:= "Carpentry",
	CARTOGRAPHY		:= "Cartography",
	COOKING			:= "Cooking",
	DETECTING_HIDDEN	:= "DetectingHidden",
	DISCORDANCE		:= "Discordance",
	EVALUATING_INTELLIGENCE	:= "EvaluatingIntelligence",
	HEALING			:= "Healing",
	FISHING			:= "Fishing",
	FORENSIC_EVALUATION	:= "ForensicEvaluation",
	HERDING			:= "Herding",
	HIDING			:= "Hiding",
	PROVOCATION		:= "Provocation",
	INSCRIPTION		:= "Inscription",
	LOCKPICKING		:= "Lockpicking",
	MAGERY			:= "Magery",
	RESISTING_SPELLS	:= "ResistingSpells",
	TACTICS			:= "Tactics",
	SNOOPING		:= "Snooping",
	MUSICIANSHIP		:= "Musicianship",
	POISONING		:= "Poisoning",
	ARCHERY			:= "Archery",
	SPIRIT_SPEAK		:= "SpiritSpeak",
	STEALING		:= "Stealing",
	TAILORING		:= "Tailoring",
	ANIMAL_TAMING		:= "AnimalTaming",
	TASTE_IDENTIFICATION	:= "TasteIdentification",
	TINKERING		:= "Tinkering",
	TRACKING		:= "Tracking",
	VETERINARY		:= "Veterinary",
	SWORDSMANSHIP		:= "Swordsmanship",
	MACE_FIGHTING		:= "MaceFighting",
	FENCING			:= "Fencing",
	WRESTLING		:= "Wrestling",
	LUMBERJACKING		:= "Lumberjacking",
	MINING			:= "Mining",
	MEDITATION		:= "Meditation",
	STEALTH			:= "Stealth",
	REMOVE_TRAP		:= "RemoveTrap"
endenum

const SKILLID__HIGHEST := 48;
