enum MOBILE_ID
	MOB_ZERO		:=  0x000,  // Not used.
	MOB_OGRE		:=  0x001,  // Ogre.
	MOB_ETTIN		:=  0x002,  // Ettin.
	MOB_ZOMBIE		:=  0x003,  // Zombie.
	MOB_GARGOYLE		:=  0x004,  // Gargoyle.
	MOB_EAGLE		:=  0x005,  // Eagle.
	MOB_BIRD		:=  0x006,  // Bird.
	MOB_ORC_LORD		:=  0x007,  // Orc Lord.
	MOB_CORPSER		:=  0x008,  // Corpser.
	MOB_DAEMON		:=  0x009,  // Daemon.
	MOB_DAEMON_SWORD	:=  0x00A,  // Daemon with sword.
	MOB_DRAGON_GREY		:=  0x00C,  // Dragon grey.
	MOB_AIR_ELEMENTAL	:=  0x00D,  // Air Elemental.
	MOB_EARTH_ELEMENTAL	:=  0x00E,  // Earth Elemental.
	MOB_FIRE_ELEMENTAL	:=  0x00F,  // Fire Elemental.
	MOB_WATER_ELEMENTAL	:=  0x010,  // Water elemental.
	MOB_ORC			:=  0x011,  // Orc.
	MOB_ETTIN_AXE		:=  0x012,  // Ettin with axe.
	MOB_GIANT_SNAKE		:=  0x015,  // Giant

	MOB_HUMAN_MALE		:=  0x190,
	MOB_HUMAN_FEMALE	:=  0x191,
	MOB_GM			:=  0x03DB
endenum
