//Cfg file used to store the areas' description

const AREAS_CFGFILE := ":areas:areas"; // OLD CFGFILE_AREAS

const AREAS_NO_DAMAGE     := "No-Damage";
const AREAS_DANGEROUS     := "Dangerous";
const AREAS_FORBIDDEN     := "Forbidden";
const AREAS_NO_GAINS      := "No-Gains";
const AREAS_NO_GATE       := "No-Gate";
const AREAS_GUARDED       := "Guarded";
const AREAS_NO_LITTERING  := "No-Littering";
const AREAS_NO_LOOTING    := "No-Looting";
const AREAS_NO_MARK       := "No-Mark";
const AREAS_NO_RECALL     := "No-Recall";
const AREAS_NO_STEALING   := "No-Stealing";

const AREAS_MOBILE_BANNED := "Banned";
