//moongate.inc

const UOBJECT_GATE := 0x6002;

const MOONGLOW_X := 4467;
const MOONGLOW_Y := 1283;
const MOONGLOW_Z := 5;

const BRITAIN_X := 1336;
const BRITAIN_Y := 1997;
const BRITAIN_Z := 5;

const JHELOM_X := 1499;
const JHELOM_Y := 3771;
const JHELOM_Z := 5;

const YEW_X := 771;
const YEW_Y := 753;
const YEW_Z := 5;

const MINOC_X := 2701;
const MINOC_Y := 693;
const MINOC_Z := 5;

const TRINSIC_X := 1828;
const TRINSIC_Y := 2948;
const TRINSIC_Z := -20;

const SKARA_X := 643;
const SKARA_Y := 2067;
const SKARA_Z := 5;

const MAGINCIA_X := 3564;
const MAGINCIA_Y := 2140;
const MAGINCIA_Z := 34;

var a_moonglow := array( MOONGLOW_X, MOONGLOW_Y, MOONGLOW_Z );
var a_britain := array( BRITAIN_X, BRITAIN_Y, BRITAIN_Z );
var a_jhelom := array( JHELOM_X, JHELOM_Y, JHELOM_Z );
var a_yew := array( YEW_X, YEW_Y, YEW_Z );
var a_minoc := array( MINOC_X, MINOC_Y, MINOC_Z );
var a_trinsic := array( TRINSIC_X, TRINSIC_Y, TRINSIC_Z );
var a_skara := array( SKARA_X, SKARA_Y, SKARA_Z );
var a_magincia := array( MAGINCIA_X, MAGINCIA_Y, MAGINCIA_Z );

var gates := array( a_moonglow, a_britain, a_jhelom, a_yew, a_minoc, a_trinsic, a_skara, a_magincia);
