/* $Id: localization.inc 642 2005-10-23 09:51:20Z panosl $
 *
 * Purpose
 * Provide localized messages
 *
 */
enum LOCALE_ENGLISH
	MSG_DONE			:= "Done",
	MSG_CANCELLED			:= "Cancelled",
	MSG_NO_CHAR			:= "That is not a character.",
	MSG_NO_MOB			:= "That is not a mobile.",
	MSG_NO_PARAM			:= "No parameter specified.",
	MSG_INVALID_PARAM		:= "Invalid parameter.",
	MSG_TARGET			:= "Target a mobile or an object.",
	MSG_TARGET_OBJ			:= "Target an object.",
	MSG_TARGET_MOB			:= "Target a mobile.",
	MSG_TARGET_CHAR			:= "Target a character.",
	MSG_TARGET_LOC			:= "Target location.",
	MSG_NOTHING_DELETE		:= "Nothing to delete.",
	MSG_SCRIPTS_UNLOADED		:= "~NUM_SCRIPTS~ scripts unloaded.",
	MSG_CONFIG_RELOADED		:= "All configuration files reloaded.",
	MSG_USE_HELP			:= "Use .help ~COMMAND_NAME~.",
	MSG_NO_HELP			:= "There is no help available for that command.",
	MSG_NO_PRIVS			:= "You lack the privileges to use ~COMMAND_NAME~.",
	MSG_WELCOME			:= "Welcome to ~WHERE~, ~WHO~!",
	MSG_SAVING_SOON			:= "Saving world state in ~TIME~ minutes.",
	MSG_SAVING_NOW			:= "Saving world state now.",
	MSG_WORLD_SAVED			:= "World state saved in ~TIME~ seconds.",
	MSG_SHAVE_INVALID_AREA		:= "Please specify an area to shave. Possible areas are:",
	MSG_GET_PROP			:= "The value of '~PROP~' is '~VALUE~'. The type is ~TYPE~.",
	MSG_NOT_EXIST			:= "'~WHAT~' doesn't exist.",

	MSG_END				:= ""
endenum
