/* $Id$
 *    Author: Unreal
 *    Created: Sunday, May 21 2006
 *    Version: 0.01
 */

const GUILD_CREATE := 0x00001;
const GUILD_DISBAND := 0x00002;
const GUILD_MESSAGE := 0x00003;
const GUILD_SET_CHARTER := 0x00004;
const GUILD_SET_WEBSITE := 0x00005;
const GUILD_ADD_MEMBER := 0x00006;
const GUILD_REMOVE_MEMBER := 0x00007;
const GUILD_REQUEST_ALLY := 0x00008;
const GUILD_REQUEST_WAR := 0x00009;