/*
        Created by *Edwards
        For FantasiaShard.com

        Edwards@FantasiaShard.com

        2010-05-10
*/

//For address book and block list
const MAX_LINES	:= 7;
//Other settings
const MAX_MESSAGES := 15;

//Others
const NEW_LETTER := 0x9000000;
const DELETE_ALL := 0x9000001;
const DELETE_MSG := 0x9000002;
const CLOSE_EMAIL := 0x9000003;
const WORD_WRAP := 0x9000004;
const SEND_EMAIL := 0x9000005;
const ADDRESS_BOOK := 0x9000006;
const BLOCK_LIST := 0x9000007;
const MASS_EMAIL := 0x9000008;
