Const BIRD_IDX := 1;
Const DAEMON_IDX := 2;
Const DRAGON_IDX := 3;
//Const EVILMAGE_IDX := 4;
Const MALE_IDX := 5;
Const FEMALE_IDX := 6;
//Const PIRATE_MALE_IDX := 7;
//Const PIRATE_FEMALE_IDX := 8;
Const LIZARD_IDX := 9;
Const ORC_IDX := 10;
Const OGRE_IDX := 11;
Const RATMAN_IDX := 12;
Const ANGEL_IDX := 13;

Const OBJ_BIRD := 0x6;
Const OBJ_DAEMON := 0x9;
Const OBJ_DAEMON_SWORD := 0xA;
Const OBJ_DRAGON_RED := 0x3D;
Const OBJ_DRAGON_GREY := 0xC; 
//Const OBJ_EVILMAGE :=
Const OBJ_MALE := 0x190;
Const OBJ_FEMALE := 0x191;
//Const OBJ_PIRATE_MALE :=
//Const OBJ_PIRATE_FEMALE :=
Const OBJ_LIZARD := 0x21;
Const OBJ_LIZARD_MACE := 0x24;
Const OBJ_LIZARD_SPEAR := 0x23;

Const OBJ_ORC := 0x11;
Const OBJ_ORC_CLUB := 0x29;
Const OBJ_ORC_CAPT := 0x7;

Const OBJ_OGRE := 0x1;

Const OBJ_RATMAN := 0x2A;
Const OBJ_RATMAN_SWORD := 0x2D;
Const OBJ_RATMAN_AXE := 0x2C;

//Const OBJ_ANGEL := 0x3a;
